CREATE TABLE users (
  id INTEGER PRIMARY KEY NOT NULL,
  firstname VARCHAR(255) NOT NULL,
  surname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE pets (
  id INTEGER PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  userId INTEGER NOT NULL,
  fluffynessScale TEXT NOT NULL,
  favourite INTEGER NOT NULL
);
